import Head from "next/head";

import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import SmallCard from "@/components/SmallCard";
import MediumCard from "@/components/MediumCard";
import LargeCard from "@/components/LargeCard";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ exploreData, cardData }) {
  return (
    <>
      <Head>
        <title>Airbnb 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl  mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explorez à proximité</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 m:grid-cols-3 xl:grid-cols-4">
            {" "}
            {exploreData.map((item, i) => (
              <SmallCard
                img={item.img}
                key={i}
                distance={item.distance}
                location={item.location}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8"> Vivez n'importe où</h2>

          <div className="flex space-x-3 overflow-x-scroll p-3 -ml-3">
            {cardData.map((card, i) => (
              <MediumCard img={card.img} key={i} title={card.title} />
            ))}
          </div>
        </section>
        <LargeCard
          img="https:/links.papareact.com/4cj"
          title="The Greatest Outdoors"
          buttonText="Get Inspired"
        />
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json().catch((err) => console.log(err))
  );

  const cardData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
    (res) => res.json()
  );

  return {
    props: { exploreData, cardData },
  };
}
